import Head from "next/head";
import { useUser } from "@supabase/auth-helpers-react";
import { supabaseClient } from '@supabase/auth-helpers-nextjs';
import { NextPageWithLayout } from "./_app";
import { ReactElement, useEffect, useState } from "react";
import AuthLayout from "../components/authLayout";

type List = {
  id: string;
  name: string;
  items: string[];
  created_at: Date;
  user_id: string;
}

const Home: NextPageWithLayout = () => {
  const {isLoading, user, error} = useUser();
  const [lists, setLists] = useState<null | List[]>(null);
  const [dataLoading, setDataLoading] = useState(true);

  const loading = isLoading || dataLoading;

  useEffect(() => {
    async function loadData() {
      const data = await supabaseClient.from<List>('list').select("*");
      setLists(data.data);
      setDataLoading(false);
    }
    loadData();
  }, []);


  console.log(lists);

  if (loading) {
    return (
      <div>
        <h1>Loading...</h1>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Shoppi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-4xl text-gray-700">Welcome to Shoppi!</h1>
        {lists ? (
          lists.map((list) => <p key={list.id}>{list.name}</p>)
        ) : (
          <p>You dont have any lists</p>
        )}
        <p>{error?.message}</p>
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
}

export default Home;
